#!/bin/sh
if [ $# -eq 0 ]; 
then 
	echo "Please pass in the name of the file to compile"
else
	echo "Compiling..."; 
	if g++ -std=c++11 $1 -o run -lX11 -lpthread -L/usr/X11/lib -L/usr/X11R6/lib -O4 -gdwarf 
	then
		./run
	else
		echo "\nIf linker error encountered, try using the commands: \n
		sudo ln -s /opt/X11/include/X11 /usr/local/include/X11 \n
		sudo apt-get install libx11-dev"; 
	fi
fi